### ISSUE TITLE
The node2vec embedding

### ISSUE THREAD

**Issue by zhenyuhe00** [kexinhuang12345/SkipGNN#1]
Hi, Kexin,
Thanks for your great work and code.
I wonder how you get the node2vec embedding. Is it based on the complete graph or based on the training sub-graph, validation sub-graph, and test sub-graph seperately?

**Comment by kexinhuang12345** [comment]
Hi, I use the training subgraph. but I think for simplicity, you could just use one-hot encoding, which I later found has similar or even better performance.

**Comment by zhenyuhe00** [comment]
Thank you for your reply. However, I wonder how to get node embeddings in dev set and test set if only using the training subgraph, since they have disjoint nodes.

**Comment by kexinhuang12345** [comment]
Hi, so we assume that the random sampling would not make a large number of nodes have zero links. So in the node2vec, we still keep the same number of nodes, just remove the edges. this way, we will still get the node embeddings.

**Comment by zhenyuhe00** [comment]
Hi, thank you for your help!
