### ISSUE TITLE
Why is there a dropout layer behind GraphConvolution layer?

### ISSUE THREAD

**Issue by qwe1997** [kexinhuang12345/SkipGNN#2]
Hi, I successfully ran the code and I find the function dropout() behind the function GraphConvolution(). However after checking the technical articles and blogs, I find that dropout() is usually used after fully connected layers, so is it really better than BatchNormalization  function in the model?

**Comment by kexinhuang12345** [comment]
i think it highly varies based on dataset. this is explored in detail in this paper: http://snap.stanford.edu/gnn-design/ checkout
